FROM registry.sh.nextgenwaterprediction.com/ngwpc/hydrofabric/hydrofabric:development

# Update packages
RUN dnf upgrade -y

# Install Python, pip, and Git
RUN dnf install -y python311 python3.11-pip python3.11-devel

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.11 1 \
    && dnf remove pip -y \
    && update-alternatives --install /usr/bin/pip pip /usr/bin/pip3.11 1

# Copy application files
COPY ./djangoApps /app/djangoApps
COPY ./Hydrofabric /app/Hydrofabric
COPY ./R /app/R
COPY ./unit_test /app/unit_test
COPY requirements.txt /app

# Install Python dependencies
RUN pip install -r /app/requirements.txt

# Set library path and expose port
ENV LD_LIBRARY_PATH=/usr/local/lib64
EXPOSE 8000

# Set the working directory
WORKDIR /app/djangoApps/

# Start the application
CMD ["python", "manage.py", "runserver"]
