version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_USER: postgres
      DB_NAME: hydrofabric_db
      DB_HOST: localhost
      DB_PASSWORD: postgres
      LD_LIBRARY_PATH: /usr/local/lib64
      S3_BUCKET: ngwpc-hydrofabric
      DJANGO_SECRET_KEY: django-insecure&z#8d*w5x8+k%mdp=d88qjtz_!=0#5ha9e3seet+id4#=*-
      DJANGO_DB_LOG_LEVEL: DEBUG
      PYTHONUNBUFFERED: 1
    volumes:
      - ..:/workspace:cached
      - ../Hydrofabric:/Hydrofabric
    command: sleep infinity
    depends_on:
      - db
    ports:
      - "8000:8000"
    network_mode: host
  
  db:
    image: postgis/postgis
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    network_mode: host

volumes:
  postgres-data:
