version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      DB_ENGINE: django.db.backends.postgresql
      #DB_USER: postgres
      #DB_NAME: hydrofabric_db
      #DB_HOST: localhost
      #DB_PASSWORD: postgres
      LD_LIBRARY_PATH: /usr/local/lib64
 
      DB_USER: joe.work
      DB_PASSWORD: N0w!sth3
      DB_HOST: 10.6.0.173
      DB_PORT: 5432
      DB_NAME: hydrofabric_db
    volumes:
      - ..:/workspace:cached
      - ../Hydrofabric:/Hydrofabric
    command: sleep infinity
#    depends_on:
#      - db
 
    # Runs app on the same network as the database container,
    # allows "forwardPorts" in devcontainer.json function
    #network_mode: service:db
    network_mode: host