# Generated by Django 5.1.1 on 2024-09-17 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HFFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gage_id', models.CharField()),
                ('hydrofabric_version', models.CharField()),
                ('filename', models.CharField()),
                ('uri', models.URLField()),
                ('domain', models.CharField()),
                ('data_type', models.CharField()),
                ('source', models.CharField()),
                ('module_id', models.CharField()),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'restapi_hffiles',
            },
        ),
    ]
