# Generated by Django 5.1.1 on 2024-10-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_param_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfeParams',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('units', models.CharField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, null=True)),
                ('limits', models.CharField(blank=True, null=True)),
                ('role', models.CharField(blank=True, null=True)),
                ('calibratable', models.BooleanField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, null=True)),
                ('min', models.CharField(blank=True, null=True)),
                ('max', models.CharField(blank=True, null=True)),
                ('nwm_name', models.CharField(blank=True, null=True)),
                ('default_value', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cfe_params',
                'db_table_comment': 'Table to contain soil parameters such as depth, satdk, etc found at confluence: https://confluence.nextgenwaterprediction.com/display/NGWPC/CFE for model CFE',
                'managed': False,
            },
        ),
    ]
